version: “3.8”
services:

  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    restart: always
    environment:
      - API_KEY=[Your API Key]
      - ZONE=[Your Domain]
      - PROXIED=true
      - PUID=1000
      - PGID=100
      
  nginx-proxy-manager:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80" 
      - "443:443"
      - "81:81"
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: [Your Username]
      DB_MYSQL_PASSWORD: [Your Password]
      DB_MYSQL_NAME: "npm"
      DISABLE_IPV6: "true"
    volumes:
      - [Your path]/nginx-proxy-manager/data:/data
      - [Your path]/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: "jc21/mariadb-aria:latest"
    container_name: nginx-proxy-manager-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: [Your Password]
      MYSQL_DATABASE: "npm"
      MYSQL_USER: [Your Username]
      MYSQL_PASSWORD: [Your Password]
    volumes:
      - [Your path]/nginx-proxy-manager/mariadb:/var/lib/mysql

  